name = "unratified-monitor"
main = "src/index.ts"
compatibility_date = "2025-03-01"
workers_dev = true
routes = [
  { pattern = "status.unratified.org", custom_domain = true },
]

[triggers]
crons = [
  "*/5 * * * *",
  "0 * * * *",
  "0 */6 * * *",
  "0 6 * * *",
]

[[d1_databases]]
binding = "DB"
database_name = "unratified-monitor"
database_id = "adbc335b-f4e0-4003-b69b-b89c4f65d654"

[vars]
ALERT_EMAIL = "kashif@kashifshah.net"
FROM_EMAIL = "monitor@kashifshah.net"
